import {test,expect} from '@playwright/test';
import {draftFixture} from './draft-fixture';
test('model choice and separated posts support copy and X handoff in both workflows',async({page},testInfo)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async(text:string)=>{(window as unknown as {copied:string}).copied=text;}}}));
 await page.route('**/api/models',route=>route.fulfill({json:{models:[{id:'example/friendly-writer',name:'Friendly Writer'}]}}));
 const requests:Record<string,string>[]=[];
 await page.route('**/api/ai',route=>{requests.push(route.request().postDataJSON());return route.fulfill({json:draftFixture});});
 await page.goto('/');
 await page.getByLabel('Find a model').fill('Friendly');
 await page.getByRole('combobox',{name:'Writing model',exact:true}).selectOption('example/friendly-writer');
 await page.getByRole('tab',{name:'Build for an audience'}).click();
 await page.getByRole('button',{name:'Generate posts',exact:true}).click();
 await expect(page.getByLabel('Post option 1',{exact:true})).toHaveValue(draftFixture.posts[0].text);
 await expect(page.getByRole('region',{name:'Reasoning for option 1'})).toContainText('share_via_copy_link');
 expect(requests[0].model).toBe('example/friendly-writer');
 const edited='Good food. Less kitchen chaos. One checklist. 🦖';
 await page.getByLabel('Post option 1',{exact:true}).fill(edited);
 await page.getByRole('button',{name:'Copy post',exact:true}).first().click();
 expect(await page.evaluate(()=>(window as unknown as {copied:string}).copied)).toBe(edited);
 const href=await page.getByRole('link',{name:'Post on X',exact:true}).first().getAttribute('href');
 expect(new URL(href!).searchParams.get('text')).toBe(edited);
 expect(new URL(href!).hostname).toBe('x.com');
 await expect(page.getByText('This explanation describes the original draft, before your edits.')).toBeVisible();
 await page.getByLabel('Post option 1',{exact:true}).fill('字'.repeat(141));
 await expect(page.locator('.post-option').first().getByRole('button',{name:'Post on X'})).toBeDisabled();
 await page.getByLabel('Post option 1',{exact:true}).fill(edited);
 await page.locator('.draft-results').scrollIntoViewIfNeeded();
 await page.screenshot({path:`test-results/${testInfo.project.name}-drafts.png`,fullPage:true});
 await page.getByRole('tab',{name:'Target a profile'}).click();
 await page.getByLabel('X profile URL or handle').fill('examplechef');
 await page.getByLabel('Public bio',{exact:true}).fill('Restaurant owner and chef.');
 await page.getByRole('button',{name:'Use pasted public text'}).click();
 await page.getByRole('button',{name:'Generate posts',exact:true}).click();
 await expect(page.getByLabel('Post option 1',{exact:true})).toHaveValue(draftFixture.posts[0].text);
 expect(requests[1].model).toBe('example/friendly-writer');
 await expect(page.getByRole('region',{name:'Reasoning for option 1'})).toContainText('not_interested');
 expect(errors).toEqual([]);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
