import {test,expect} from '@playwright/test';
test('analysis, score overrides, eligibility, custom audiences, and reverse brief',async({page},testInfo)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');
 await expect(page.getByRole('heading',{name:'Find your audience.'})).toBeVisible();
 await expect(page.getByRole('button',{name:'Inspect AI builders'})).toBeVisible();
 await page.getByLabel('Post text').fill('Bitcoin crypto markets trading portfolio');
 await expect(page.getByText('Inputs changed. Analyze again to update results.')).toBeVisible();
 await page.getByRole('button',{name:'Analyze audience fit'}).click();
 await expect(page.locator('.audience-row').first()).toContainText('Market watchers');
 await page.getByRole('button',{name:'Inspect Market watchers'}).click();
 await page.getByLabel('Report assumed input').fill('1');
 await page.getByRole('button',{name:'Apply assumptions'}).click();
 await expect(page.locator('.audience-row').first()).not.toContainText('Market watchers');
 await page.locator('summary').click();
 await page.getByLabel('Age in hours').fill('49');
 await page.getByRole('button',{name:'Analyze audience fit'}).click();
 await expect(page.locator('.audience-row').first()).toContainText('Filtered');
 await page.getByLabel('Age in hours').fill('0');
 await page.getByRole('button',{name:'Create a custom archetype',exact:true}).click();
 await page.getByLabel('Who do you have in mind?').fill('Gardeners who enjoy composting and native plants');
 await page.getByRole('button',{name:'Create deterministic archetype'}).click();
 await page.getByRole('tab',{name:'Build for an audience'}).click();
 await expect(page.getByLabel('Generated prompt')).toHaveValue(/composting/);
 await page.getByLabel('What’s the post about?').fill('A beginner guide to composting');
 await expect(page.getByLabel('Generated prompt')).toHaveValue(/A beginner guide to composting/);
 await page.screenshot({path:`test-results/${testInfo.project.name}-studio.png`,fullPage:true});
 expect(errors).toEqual([]);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
test('file import, API validation, and key setup',async({page,request},testInfo)=>{
 await page.goto('/');
 await page.locator('input[type=file]').setInputFiles({name:'post.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({text:'Tennis players and soccer fans have a match today.'}))});
 await expect(page.getByLabel('Post text')).toHaveValue(/Tennis players/);
 await page.getByRole('button',{name:'Analyze audience fit'}).click();
 await expect(page.locator('.audience-row').first()).toContainText('Sports fans');
 await page.screenshot({path:`test-results/${testInfo.project.name}-analysis.png`,fullPage:true});
 const noKey=await request.post('/api/ai',{data:{action:'draft',prompt:'Write a helpful post about AI.'}});
 expect(noKey.status()).toBe(401);expect((await noKey.json()).error).toContain('OpenRouter');
 const invalid=await request.post('/api/ai',{data:{action:'not-allowed'}});expect(invalid.status()).toBe(400);
 await page.getByRole('tab',{name:'Build for an audience'}).click();
 await page.getByRole('button',{name:'Generate with Sonnet'}).click();
 await expect(page.getByRole('dialog',{name:'Connect your writing assistant'})).toBeVisible();
 await page.getByLabel('OpenRouter API key').fill('sk-or-test-placeholder-not-a-real-key');
 await page.getByRole('button',{name:'Done',exact:true}).click();
 // Deliberate mock: proves client wiring without spending a real provider credential.
 await page.route('**/api/ai',route=>route.fulfill({json:{text:'1. MOCK TEST DRAFT',model:'test-sonnet-model'}}));
 await page.getByRole('button',{name:'Generate with Sonnet'}).click();
 await expect(page.getByText('1. MOCK TEST DRAFT', {exact:true})).toBeVisible();
 expect(await page.evaluate(()=>JSON.stringify(localStorage)+JSON.stringify(sessionStorage))).not.toContain('sk-or');
});
