'use client';
import {useState} from 'react';
import LengthPicker from './LengthPicker';
import type {PostLength} from '@/lib/writing';
import DraftResults from './DraftResults';
import type {WriterVoice} from '@/lib/voice';
import type {DraftResponse} from '@/lib/drafts';
import {Copy,ExternalLink,LoaderCircle,Search,Sparkles,UserRound,Info} from 'lucide-react';
import {parseHandle,profileInterests,profilePrompt,type PublicProfile} from '@/lib/profile';
type Props={voice:WriterVoice;generate:(prompt:string,length:PostLength)=>Promise<DraftResponse|null>};
export default function ProfileTab({generate,voice}:Props){
 const [contentContext,setContentContext]=useState('');
 const [length,setLength]=useState<PostLength>('expanded');
 const [input,setInput]=useState('');const [profile,setProfile]=useState<PublicProfile|null>(null);
 const [bio,setBio]=useState('');const [posts,setPosts]=useState('');const [interests,setInterests]=useState('');
 const [topic,setTopic]=useState('A useful, practical insight related to the selected interests');const [tone,setTone]=useState('Clear and conversational');const [busy,setBusy]=useState(false);
 const [error,setError]=useState('');const [notice,setNotice]=useState('');const [draft,setDraft]=useState<DraftResponse|null>(null);
 const selected=[...new Set(interests.split(',').map(x=>x.trim()).filter(Boolean))].slice(0,15);
 const prompt=profile&&selected.length&&topic.trim()?profilePrompt(profile,selected,topic,tone,voice,length,contentContext):'';
 function accept(p:PublicProfile){setProfile(p);setBio(p.bio);setPosts(p.posts.map(x=>x.text).join('\n\n'));setInterests(profileInterests(p).join(', '));setDraft(null);setNotice(p.warning||'Evidence loaded. Review the suggested interests before copying your prompt.');}
 async function load(){setError('');setNotice('');setBusy(true);setProfile(null);setDraft(null);try{parseHandle(input);const response=await fetch('/api/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile:input})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Could not import this profile.');accept(result.profile);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function manual(){setError('');try{const username=parseHandle(input);if(!bio.trim()&&!posts.trim())throw new Error('Paste the public bio or at least one post excerpt.');accept({username,name:username,bio:bio.slice(0,1000),posts:posts.split(/\n\s*\n/).map(p=>p.trim()).filter(Boolean).slice(0,10).map((text,i)=>({id:`pasted-${i}`,text:text.slice(0,1200)})),source:'pasted'});}catch(e){setError((e as Error).message);}}
 async function copy(){try{await navigator.clipboard.writeText(prompt);setNotice('Profile-targeted prompt copied.');}catch{setError('Clipboard access failed. Select the prompt text and copy it manually.');}}
 return <div className="profile-workspace">
  <div className="profile-limit"><Info size={18}/><p>Public posts suggest interests—not someone’s private For You feed. Use this to write for relevant interests, without a placement guarantee.</p></div>
  {error&&<div className="alert error" role="alert">{error}</div>}{notice&&<div className="alert notice" role="status">{notice}</div>}
  <div className="studio-grid"><section className="card"><div className="section-title"><span className="step">01</span><h2>Public profile</h2><UserRound size={18}/></div>
   <label className="field">X profile URL or handle<input value={input} maxLength={200} onChange={e=>{setInput(e.target.value);setProfile(null);setBio('');setPosts('');setInterests('');setDraft(null);setNotice('');}} placeholder="https://x.com/username or @username" autoComplete="off"/></label>
   <button className="primary" disabled={!input.trim()||busy} onClick={()=>void load()}>{busy?<LoaderCircle className="spin" size={17}/>:<Search size={17}/>}Import public profile</button>
   <details className="context-details" open={!profile}><summary>Paste public text instead</summary><p className="hint">Paste only publicly available text. Separate up to 10 post excerpts with a blank line; each excerpt uses its first 1,200 characters.</p><label className="field">Public bio<textarea rows={3} value={bio} maxLength={1000} onChange={e=>setBio(e.target.value)} placeholder="Copy the public profile bio…"/></label><label className="field">Public post excerpts<textarea rows={6} value={posts} maxLength={12000} onChange={e=>setPosts(e.target.value)} placeholder="Paste original public posts, separated by blank lines…"/></label><button className="secondary" disabled={busy} onClick={manual}>Use pasted public text</button><p className="hint">Edits above take effect after you select “Use pasted public text.”</p></details>
   {profile&&<div className="profile-evidence"><div className="mini-label">EVIDENCE IN USE</div><h3>@{profile.username}</h3><p className="hint">{profile.source==='x-api'?'Imported from X API':'User-pasted · not independently verified'} · {profile.posts.length} post excerpts</p>{profile.fetchedAt&&<p className="hint">Retrieved {new Date(profile.fetchedAt).toLocaleString()}</p>}<p>{profile.bio||'No bio supplied.'}</p><a className="text-button" href={`https://x.com/${profile.username}`} target="_blank" rel="noreferrer">View public profile<ExternalLink size={14}/></a><details><summary>Review post excerpts</summary>{profile.posts.map((p,i)=><article key={p.id}><p>{p.text}</p>{profile.source==='x-api'&&<a className="text-button" href={`https://x.com/${profile.username}/status/${p.id}`} target="_blank" rel="noreferrer">Source post {i+1}<ExternalLink size={12}/></a>}</article>)}</details></div>}
  </section><section className="card brief-card"><div className="section-title"><span className="step">02</span><h2>Profile-targeted prompt</h2></div><label className="field">Interests to write for<textarea rows={3} maxLength={600} value={interests} disabled={!profile} onChange={e=>{setInterests(e.target.value);setDraft(null);}} placeholder="Import or paste evidence, then review comma-separated interests…"/></label><p className="hint">Suggestions use literal topic matches from X-Rex’s dictionaries. Edit them using explicit public evidence. No matches? Add relevant interests yourself; we won’t invent them.</p><label className="field">Your post topic<textarea rows={3} value={topic} maxLength={1200} onChange={e=>{setTopic(e.target.value);setDraft(null);}} placeholder="For example: reducing restaurant food waste with a daily inventory check"/></label><label className="field">Facts, examples &amp; media context (optional)<textarea rows={4} maxLength={3000} value={contentContext} onChange={e=>{setContentContext(e.target.value);setDraft(null);}} placeholder="Audience problem, a real example, facts you can support, or what your image / video / quoted post shows…"/></label><p className="hint">Add link-preview or quoted text yourself. URLs and media descriptions are not fetched or independently verified.</p><label className="field">Post voice<select value={tone} onChange={e=>{setTone(e.target.value);setDraft(null);}}><option>Clear and conversational</option><option>Practical and educational</option><option>Thoughtful and analytical</option><option>Playful and concise</option></select></label><LengthPicker value={length} onChange={value=>{setLength(value);setDraft(null);}}/><p className="hint">Includes content markers with pinned sources, separate writing-quality notes, and a specific explanation for each draft.</p><div className="brief-preview"><div className="mini-label">LLM-READY PROMPT</div><textarea readOnly aria-label="Profile generation prompt" value={prompt||'Load public evidence, review the interests, and add your topic to generate a prompt.'}/></div><button className="primary" disabled={!prompt} onClick={()=>void copy()}><Copy size={17}/>Copy profile prompt</button><button className="secondary profile-generate" disabled={!prompt||busy} onClick={async()=>{setBusy(true);try{const result=await generate(prompt,length);if(result){setDraft(result);}}finally{setBusy(false);}}}>{busy?<LoaderCircle className="spin" size={17}/>:<Sparkles size={17}/>}Generate posts</button><p className="hint">The brief is deterministic for the evidence and interests you choose. Drafts use your selected OpenRouter model and can vary.</p>{draft&&<DraftResults result={draft}/>}</section></div>
 </div>;
}
