'use client';
import {useEffect,useRef,useState} from 'react';
import Image from 'next/image';
import {Send,X,LoaderCircle} from 'lucide-react';
import AppDialog from './AppDialog';
import {usePaidPaused} from './PaidAccess';
import {HELP_LABELS,helpSchema,type HelpAction} from '@/lib/help';
type Message={role:'user'|'assistant';content:string;actions?:HelpAction[]};
const welcome:Message={role:'assistant',content:'Hey, I’m X-Rex. 🦖 Want to find your audience, make a draft sound like you, or understand those algorithm markers?',actions:['voice','create','tour']};
export default function RexAssistant({model,tab,hasVoice,onAction}:{model:string;tab:string;hasVoice:boolean;onAction:(action:HelpAction)=>void}){
 const [open,setOpen]=useState(false),[messages,setMessages]=useState<Message[]>([welcome]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const end=useRef<HTMLDivElement>(null);
 const paused=usePaidPaused();
 useEffect(()=>{if(open)end.current?.scrollIntoView({block:'nearest'});},[messages,busy,open]);
 async function send(){if(!input.trim()||busy||paused)return;const question=input.trim();const history=[...messages,{role:'user' as const,content:question}].slice(-12);setMessages(history);setInput('');setBusy(true);setError('');try{const response=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'help',model,messages:history.map(({role,content})=>({role,content})),context:{tab,hasVoice}})});const data=await response.json();if(!response.ok)throw new Error(data.error||'X-Rex could not respond.');const result=helpSchema.parse(data);setMessages(m=>[...m,{role:'assistant',content:result.reply,actions:result.actions}]);}catch(e){setMessages(m=>m.slice(0,-1));setError((e as Error).message);setInput(question);}finally{setBusy(false);}}
 function navigate(action:HelpAction){setOpen(false);onAction(action);}
 return <><button className="rex-launcher" onClick={()=>setOpen(true)} aria-label="Talk to X-Rex"><Image src="/x-rex.webp" alt="" width={38} height={38}/><span>Talk to X-Rex</span></button><AppDialog open={open} onClose={()=>setOpen(false)} label="Talk to X-Rex" className="rex-dialog"><header className="rex-chat-header"><Image src="/x-rex.webp" alt="" width={48} height={48}/><div><h2>Talk to X-Rex</h2><small>Your guide to better posts</small></div><button className="icon-button" aria-label="Close X-Rex chat" onClick={()=>setOpen(false)}><X size={20}/></button></header><div className="rex-chat-scroll" role="log" aria-label="X-Rex conversation" aria-live="polite">{messages.map((message,i)=><div key={i} className={`rex-message ${message.role}`}><small>{message.role==='assistant'?'X-REX':'YOU'}</small><p>{message.content}</p>{message.actions&&<div className="rex-actions">{message.actions.map(action=><button key={action} onClick={()=>navigate(action)}>{HELP_LABELS[action]}</button>)}</div>}</div>)}{busy&&<div className="rex-thinking" role="status"><LoaderCircle className="spin" size={16}/>X-Rex is thinking…</div>}{error&&<div className="alert error" role="alert">{error} Your question is ready to retry.</div>}{paused&&<div className="alert error" role="status">X-Rex chat is paused by the site owner. The navigation shortcuts below still work.</div>}<div ref={end}/></div><div className="rex-shortcuts"><button onClick={()=>navigate('method')}>Explain the scores</button><button onClick={()=>navigate('profile')}>Find a reader</button><button disabled={busy} onClick={()=>{setMessages([welcome]);setError('');setInput('');}}>Clear chat</button></div><form className="rex-composer" onSubmit={e=>{e.preventDefault();void send();}}><label className="sr-only" htmlFor="rex-question">Ask X-Rex</label><textarea id="rex-question" rows={2} maxLength={2000} value={input} onChange={e=>setInput(e.target.value)} placeholder="How do I write for restaurant owners?" onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send();}}}/><button className="primary" aria-label="Send to X-Rex" disabled={busy||paused||!input.trim()} type="submit"><Send size={18}/></button></form><p className="rex-chat-note">Uses your selected model · Chat lasts for this session<br/>X-Rex can guide you; it cannot publish or change settings.</p></AppDialog></>;
}
