'use client';
import {useEffect,useRef,useState} from 'react';
import {PenLine,Search,Trash2,Check,LoaderCircle} from 'lucide-react';
import {EMPTY_VOICE,voiceSchema,type WriterVoice} from '@/lib/voice';
const STORAGE='xrex:voice:v1';
export default function WriterProfile({onChange,request,disabled}:{onChange:(voice:WriterVoice)=>void;request:number;disabled:boolean}){
 const [saved,setSaved]=useState(EMPTY_VOICE),[form,setForm]=useState(EMPTY_VOICE),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const ref=useRef<HTMLDetailsElement>(null);
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE);if(raw){const value=voiceSchema.safeParse(JSON.parse(raw));if(value.success){setSaved(value.data);setForm(value.data);onChange(value.data);}}}catch{setNotice('Browser storage is unavailable. You can still use a voice for this session.');}},[onChange]);
 useEffect(()=>{if(request){setOpen(true);ref.current?.scrollIntoView({behavior:'smooth',block:'start'});}},[request]);
 async function load(){setBusy(true);setError('');setNotice('');try{const response=await fetch('/api/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile:form.handle})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Could not import your profile.');const examples=data.profile.posts.slice(0,5).map((p:{text:string})=>p.text).join('\n\n').slice(0,6000);setForm(f=>({...f,handle:`@${data.profile.username}`,examples}));setNotice(data.profile.warning||'Examples imported. Review them, then save your voice.');if(!examples)setError('No writing examples were returned. Paste a few of your posts below.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function save(){const parsed=voiceSchema.safeParse(form);if(!parsed.success||!form.examples.trim()){setError('Add at least one writing example before saving.');return;}setSaved(form);onChange(form);setError('');try{localStorage.setItem(STORAGE,JSON.stringify(form));setNotice('Your voice is saved on this browser and applied to both writing workflows.');}catch{setNotice('Voice applied for this session. Browser storage is unavailable.');}}
 function remove(){setSaved(EMPTY_VOICE);setForm(EMPTY_VOICE);onChange(EMPTY_VOICE);setError('');try{localStorage.removeItem(STORAGE);setNotice('Saved voice removed.');}catch{setNotice('Voice cleared for this session. Browser storage could not be cleared.');}}
 return <details ref={ref} className="writer-profile" open={open} onToggle={e=>setOpen(e.currentTarget.open)}><summary><span className="writer-icon"><PenLine size={19}/></span><span><strong>Your writing style</strong><small>{saved.examples?`${saved.handle||'Your examples'} · Voice applied`:'Make every draft sound more like you'}</small></span><span className="voice-badge">{saved.examples?'EDIT VOICE':'SET UP'}</span></summary><div className="writer-form"><p className="hint">Add your own profile or paste your writing. Examples guide the model’s style; they do not train it or change audience scores.</p><div className="writer-import"><label className="field">Your X profile<input value={form.handle} maxLength={200} onChange={e=>setForm(f=>({...f,handle:e.target.value}))} placeholder="@yourhandle or your public profile URL" disabled={busy}/></label><button className="secondary" disabled={!form.handle.trim()||busy||disabled} onClick={()=>void load()}>{busy?<LoaderCircle size={16} className="spin"/>:<Search size={16}/>}Import my posts</button></div><label className="field">Your writing examples<textarea rows={5} maxLength={6000} value={form.examples} disabled={busy} onChange={e=>setForm(f=>({...f,examples:e.target.value}))} placeholder="Paste 2–5 posts you wrote, separated by blank lines…"/></label><label className="field">Style preferences (optional)<textarea rows={2} maxLength={800} value={form.notes} onChange={e=>setForm(f=>({...f,notes:e.target.value}))} placeholder="Short sentences, dry humor, no hashtags…"/></label><div className="writer-buttons"><button className="primary" disabled={!form.examples.trim()||busy||disabled} onClick={save}><Check size={16}/>Save my voice</button><button className="secondary" disabled={busy||disabled} onClick={remove}><Trash2 size={16}/>Remove voice</button></div>{error&&<p className="alert error" role="alert">{error}</p>}{notice&&<p className="hint" role="status">{notice}</p>}<p className="hint">Saved on this browser until removed. Saved examples are included in copied prompts and sent to your selected model when you generate posts. Unsaved edits are not applied.</p></div></details>;
}
